Implement warning logging level (#2323)
* Make version.py bittensor import independent

* Update setup.py, replace file with the __version__

* Update settings.py

* Make axon independent of bittensor import. Fix axon tests.

* Make chain_data.py independent of bittensor import. Fix chain_data tests.

* Make dendrite.py independent of bittensor import. Fix dendrite tests.

* Make staking.py independent of bittensor import. Fix staking tests.

* Make subtensor.py independent of bittensor import. Fix subtensor tests.

* Make prometheus.py independent of bittensor import. Fix prometheus tests.

* Axon refactoring

* Move subnets.py into bittensor/utils since this module is not used within the bittensor package, but is actively used by the community.

* Make synapse.py independent of bittensor import. Fix synapse tests.

* Make tensor.py independent of bittensor import. Fix tensor tests.

* Change name `bittensor.utils.hash` -> `bittensor.utils.get_hash`

* Moved from using `import bittensor` (withing bittensor codebase) to direct imports of modules and other objects. It helped to avoid namespace conflicts.

* Add backwards compatibility for 'bittensor.api.extrinsics' as 'bittensor.extrinsics'

* Move the contents of `wallet_utils.py` to `bittensor/utils/__init__.py`, since it is used directly from utils.

* Delete `bccli` staff and related tests. Fix setup.py.

* Fix tests.

* Makes the `bittensor.utils.mock` subpackage available as `bittensor.mock` for backwards compatibility.

* Check for participation before nomination call

* Ruff formatting. Fix ruff's complaints.

* Removing obsolete, unused (community and bittensor) code

* Move backwards compatibility related content to `bittensor/utils/backwards_compatibility` subpackage

* btlogging/loggingmachine.py improvement from https://github.com/opentensor/bittensor/pull/2155

* Fixes after `Merge streaming fix to staging` from https://github.com/opentensor/bittensor/pull/2183

* Review fix.

* Remove black from dev requirements.

* black back

* Remove space from prod.txt. Remove black from dev.txt

* Add dendrite reference to backwords compatibility

* Fix the usage of env vars in default settings.

* ruff

* Change the subpackage name to `deprecated`

* Update __version__ until 8.0.0

* Move `subnets.py` to `bittensor/utils` as it is considered more utility than deprecated.

* Rename test module

* Add aliases mapping test

* ruff

* Init: Adds initial e2e tests

* Ruff

* Fixes LOCALNET_SH_PATH env_var

* Adds module description

* Adds commit-reveal back and adds e2e for liquid alpha & commit reveal

* Review suggestions implemented

* Fixes logging string

* Enhance: Switch from format() to f-strings

* ruff

* Optimize imports

* Add the opportunity to run `python - m bittensor`

* replace deps link from https to ssh

* Fixes metagraph save/load for neurons, added e2e tests (metagraph + extrinsics)

* Renamed test

* Adds missing statements

* increase subtensor.py test coverage until 80%

* ruff

* add tests

* ruff

* add tests _do_serve_prometheus

* add tests neuron_for_uid

* sort tests by group

* sort tests by group

* remove unused import

* add test for `get_neuron_for_pubkey_and_subnet`

* Add unit tests to subtensor.py

* Fix ruff + `test_do_set_weights_no_waits` description

* add tests

* ruff + add tests

* ruff

* add test

* fix unused imports

* Config refactoring

* Remove duplicated tests

* add test

* remove duplicated import

* remove unused functions

* remove unused functions + add tests

* ruff

* fix type annotation

* add tests

* Add tests and remove unused functions

* fix test

* ruff

* Add balance tests, small refactoring

* Add init test for bittensor

* ruff

* Add tests for utils.weight_utils.py

* add tests for bittensor.utils.subnets

* ruff

* update test file

* Decoupling chain_data.py to sub-package

* Fix test

* ruff

* review fix

* update `requirements/prod.txt`

* Update localnet entrypoint port

* Add substrate reconnection logic

* Fix tests + add tests

* Ruff formatter

* add docstring to the decorator

* update requirements

* update requirements

* update requirements

* cleanup __init__.py

* - move `extrinsics` from deprecated into `bittensor/core`;
- update `deprecated` sub-package to `deprecated.py` module.

* update ssh to https in requirements

* add reconnection logic for correctly closed connection

* remove unused import

* fix pagination

* Move do_* methods into the related extrinsic module (commit_weights.py).

* Move do_* methods into the related extrinsic module (bittensor/core/extrinsics/set_weights.py).

* Move do_* methods into the related extrinsic module (bittensor/core/extrinsics/transfer.py). + ruff

* Move do_* methods into the related extrinsic module (bittensor/core/extrinsics/serving.py)

* Move do_* methods into the related extrinsic module (bittensor/core/extrinsics/prometheus.py)

* bug fixes

* extrinsics refactoring

* bug fix

* ruff

* fix

* removed exit sys call for ConnectionRefusedError in _get_substrate

* remove unused import

* change the log message

* Corrected arguments order in logging methods + test

* fix integration test

* ruff

* comments fixes

* fix `bittensor/core/subtensor.py:445: error: Argument "logger" to "retry" has incompatible type "LoggingMachine"; expected "Logger | None"  [arg-type]`

* integrate `bt_decode` into BTSDK

* fix logger linter checker

* Reverts logging enhancement

* remove unused code and tests

* remove unused imports

* modification of error formatter, moved the submit_extrinsic call to utils.py, fixed the subtensor.py regarding extrinsics calls, fixed tests

* ruff

* Improved logic for concatenating message, prefix, and suffix in bittensor logging + test

* fix + ruff

* remove unused import

* improve btlogging concat test

* docs AxonInfo

* docs DelegateInfo

* DelegateInfoLite

* IPInfo

* NeuronInfo

* NeuronInfo + NeuronInfoLite

* PrometheusInfo

* ProposalVoteData

* ScheduledColdkeySwapInfo

* ProposalVoteData

* StakeInfo

* StakeInfo + SubnetHyperparameters

* bittensor/core/chain_data/utils.py

* bittensor/core/axon.py

* bittensor/core/axon.py

* bittensor/core/config.py

* bittensor/core/dendrite.py

* bittensor/core/metagraph.py

* bittensor/core/stream.py

* bittensor/core/subtensor.py

* bittensor/core/synapse.py

* bittensor/core/tensor.py

* replace Tuple, Dict, List, Set to python native types

* bittensor/__init__.py

* bittensor/utils/weight_utils.py

* bittensor/utils/version.py

* bittensor/utils/btlogging

* fix

* remove wrong `optional` from docstring's annotations

* apply camel case rule

* bittensor/core/extrinsics/commit_weights.py

* bittensor/core/extrinsics/prometheus.py

* bittensor/core/extrinsics/serving.py

* axon improvement (add annotation)

* README updates for SDK

* bittensor/core/extrinsics/set_weights.py

* bittensor/core/extrinsics/transfer.py

* fix

* weight_utils.py

* check up and fix

* fix Axon Signature

* fix axon

* delete unused import

* update GPG

* remove unused code, remove old tests, add new tests

* fix

* temp commented line

* fix review comments

* fix review comments

* Adding TOC and working in review comments.

* Adding installation options

* Formatting adjustments for html display

* Ruff formatted

* Example reformatted

* update metagraph

* update dendrite.py

* Update README.md

Co-authored-by: garrett-opentensor <156717492+garrett-opentensor@users.noreply.github.com>

* Update README.md

Co-authored-by: garrett-opentensor <156717492+garrett-opentensor@users.noreply.github.com>

* Update README.md

* Update axon.py

* fix tests/unit_tests/test_axon.py

* Update README.md

* set `WARNING` level ad default logging level

* fix test

* implement warning version, do info the same as default level

* fix

* ruff

* cleanup

* Change warning to debug for local connection information

* update deps

* remove unused file

---------

Co-authored-by: ibraheem-opentensor <165814940+ibraheem-opentensor@users.noreply.github.com>
Co-authored-by: ibraheem-opentensor <ibraheem@opentensor.dev>
Co-authored-by: Watchmaker <rajk@opentensor.dev>
Co-authored-by: garrett-opentensor <156717492+garrett-opentensor@users.noreply.github.com>